#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e77101ec7459402dad12d2ecde566f9c" }
]
